apiVersion: v1
name: unnecessary-ly-backend
version: 0.0.1
description: Java backend for an unnecessary brick breaker clone.
type: application
home: https://coffeecodecontribute.github.io/unnecessary.ly-backend-java/
sources:
  - git@github.com:coffeecodecontribute/unnecessary.ly-backend-java.git
maintainers:
  - name: Felix Pojtinger
    email: felix@pojtinger.com
    url: https://felix.pojtinger.com
appVersion: 0.0.1
